# Generated by Django 3.0.7 on 2020-09-06 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=50)),
                ('validFlag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('validFlag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('validFlag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('validFlag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validFlag', models.BooleanField(default=False)),
                ('recipeId', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.Recipe')),
                ('stepId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Step')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='usersId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.User'),
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validFlag', models.BooleanField(default=False)),
                ('ingredientId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Ingredient')),
                ('recipeId', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.Recipe')),
            ],
        ),
    ]
