# Generated by Django 3.0.7 on 2020-09-06 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='recipeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Recipe'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='recipeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Recipe'),
        ),
    ]
