# Generated by Django 3.0.7 on 2020-09-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200906_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='validFlag',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='validFlag',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='validFlag',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='validFlag',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='validFlag',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='validFlag',
            field=models.BooleanField(default=True),
        ),
    ]
