# Generated by Django 3.0.7 on 2021-02-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200913_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='stepNo',
            field=models.IntegerField(default=True),
        ),
    ]
