# Generated by Django 3.0.7 on 2021-03-16 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_steps_stepno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='ingredientId',
            new_name='ingredient',
        ),
    ]
