# Generated by Django 3.0.7 on 2021-03-25 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210316_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='ingredients',
            old_name='ingredient',
            new_name='ingredientId',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='validFlag',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='validFlag',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='validFlag',
        ),
        migrations.RemoveField(
            model_name='step',
            name='validFlag',
        ),
        migrations.RemoveField(
            model_name='steps',
            name='validFlag',
        ),
        migrations.RemoveField(
            model_name='user',
            name='validFlag',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='ingredientGroup',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unitId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.Unit'),
            preserve_default=False,
        ),
    ]
