# Generated by Django 3.0.6 on 2020-05-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
        migrations.AddField(
            model_name='recipe',
            name='IngredientsId',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='stepId',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='userId',
            field=models.CharField(default='', max_length=20),
        ),
    ]
